### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by shgubar** [magcode/daikin-mqtt#14]
Hello

I have several questions:
1) regarding **MQTT** - what to do if the broker requires a username and password?
2) regarding inclusion only when there is a clear `power/set 'on'` and then not when changing only `mode/set 'cool to dry'`?
3) are you planning to create a docker container?

Thanks for your code.

**Comment by magcode** [comment]
Hello, 

1) either implement it yourself and create a PR or you look out for some forks which implement this already
2) I don't understand this questions, sorry
3) no

**Comment by shgubar** [comment]
> 2. I don't understand this questions, sorry

I meant to change the mode without turning on the air conditioner.

Another question: can you provide correct instructions for compiling your code?

Thanks.
