### ISSUE TITLE
 Retanied messages are needed? Side effect.

### ISSUE THREAD

**Issue by FulvioSpelta** [magcode/daikin-mqtt#6]
I've seen that the messages are published as "retained".
IMHO this is not necessary because the "subscriber" will receive:
- The LWT (or the last state) message in order to know immediately know the state of the device.
- Updated data at the defined interval
Furher the "retained" messages could be very old creating noise in the subscriber.

Side effect
Every test/device remain in the broker db and is delivered at every connection at every subscriber; in this example i've done a test using ac-room1 deviceid and now every subscribers (different mqtt clientid) receive a full set of data at every connection:
![image](https://user-images.githubusercontent.com/1832999/83490916-2418e780-a4b1-11ea-84cc-d87ecefbe5b7.png)
![image](https://user-images.githubusercontent.com/1832999/83490925-28450500-a4b1-11ea-8e41-d76244be74d3.png)

**Comment by magcode** [comment]
I understood the convention that "retained" is the default
https://homieiot.github.io/specification/#qos-and-retained-messages

I'm aware of this effect that test devices stay in the broker. Not sure how to solve it.

**Comment by FulvioSpelta** [comment]
As the standard is asking for this implementation I suggest to leave it untouched,
I'll clean the broker db.

The only concern is about the overall behavior of the gateway: because the "state" miss the LWT message, when a messages consumer connect to the broker it recevive a full set of measure and a "ready" state that will make it consider the gateway to be up&running even if it is completely off or disconnected.

**Comment by magcode** [comment]
I made retained=false and qos=0 as the default now. You can set it back to retained and qos=1 in the properties file (see readme)
