### ISSUE TITLE
MQTT Topic for sending commands

### ISSUE THREAD

**Issue by FulvioSpelta** [magcode/daikin-mqtt#7]
In the readme.md are documented the topics:
![image](https://user-images.githubusercontent.com/1832999/83497115-4b27e700-a4ba-11ea-9623-d8b17872dde7.png)

In my test I can send commands to topics without the $ sign (as reported in the log):
![image](https://user-images.githubusercontent.com/1832999/83497286-89bda180-a4ba-11ea-91c4-dabf1d2a1272.png)

**Comment by magcode** [comment]
docs will be fixed. Thanks for reporting.
